scaf1/config/routes.rb
Rails.application.routes.draw do
  root 'cars#index'
  resources :cars
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

scaf1/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

scaf1/app/models/car.rb
class Car < ApplicationRecord
end

scaf1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

scaf1/app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.save
    @cars = Car.all
  end

  def show
    @car =Car.find(params[:id])
  end

  def edit
    @car = Car.find(params[:id])
  end
  def update
    @car=Car.find(params[:id])
    if @car.update(car_params)
      redirect_to @car      
    else
      render :edit ,status: :unprocessable_entity
    end
  end

  def destroy
    @car= Car.find(params[:id])
    @car.destroy

    redirect_to root_path, status: :see_other

  end
  private
  def car_params
    params.require(:car).permit(:id,:m_name,:color,:c_name,:c_type,:speed,:ecofriendly)
  end
end

scaf1/app/helpers/application_helper.rb
module ApplicationHelper
end

scaf1/app/helpers/cars_helper.rb
module CarsHelper
end

scaf1/app/views/cars/_car.html.erb
<% @cars.each do |car|%>

<tr>
<td align="center"><%= car.c_name+" "+car.m_name%></td>

<td align="center"><%= link_to "Show", car %></td>

<td align="center"><%= link_to "Edit", edit_car_path(car) %></td>
<td align="center"><%= link_to "delete", car, method: :delete,remote:true,data: { confirm: 'Are you sure?' }%></td>
</tr>

<%end%>

scaf1/app/views/cars/_form.html.erb
<%= form_with(model: @car,id:"new_car",local: false) do |form|%>
<!-- Errors code -->
<% if car.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

	<ul>
		<% car.errors.each do |error| %>
		<li><%= error.full_message %></li>
		<% end %>
	</ul>
	<%end%>
</div>
<!-- Form code start here -->

<div class="container p-5 my-5 bg-dark text-white">
	<strong><%= form.label :" Company name  :"%></strong><%= form.text_field :c_name %>
</div>
<div class="container p-5 my-5 bg-primary text-white">
	<strong><%= form.label :" Model name    :"%></strong><%= form.text_field :m_name %>
</div>
<div class="container p-5 my-5 bg-dark text-white">
	<strong><%= form.label :"Eco Friendly   :"%></strong><br>
	<%= form.radio_button :ecofriendly, " Yes " %>
	<%= form.label :Yes %>
	<br>
	<%= form.radio_button :ecofriendly, " No " %>
	<%= form.label :No %>
</div>
<div class="container p-5 my-5 bg-white text-black">
	<strong><%= form.label :"Car Type       :"%></strong><br>
	<%= form.radio_button :car_type, "Sedan" %>
	<%= form.label :Sedan %>
	<br>


	<%= form.radio_button :car_type, "Hatch Back" %>
	<%= form.label :Hatch_Back %>	
	<br>	

	<%= form.radio_button :car_type, "SUV" %>
	<%= form.label :SUV %>	
	<br>	

	<%= form.radio_button :car_type, "MUV" %>
	<%= form.label :MUV %>	
	<br>

	<%= form.radio_button :car_type, "Super" %>
	<%= form.label :Super %>
	<br>


	<%= form.radio_button :car_type, "Sports" %>
	<%= form.label :Sports %>
	<br>		

	<%= form.radio_button :car_type, "Convertible" %>
	<%= form.label :Convertible %>
	<br>		

	<%= form.radio_button :car_type, "Crossover" %>
	<%= form.label :Crossover %>
	<br>

	<%= form.radio_button :car_type, "Mussle car" %>
	<%= form.label :Mussle_car %>
	<br>

	<%= form.radio_button :car_type, "Coupe" %>
	<%= form.label :Coupe %>
	<br>

	<%= form.radio_button :car_type, "Luxery" %>
	<%= form.label :Luxery %>

</div>
<div class="container p-5 my-5 bg-dark text-white">
	<strong><%= form.label :" Speed  :"%></strong><%= form.text_field :speed %>
</div>
<div class="container p-5 my-5 bg-primary text-white">
	<strong><%= form.label :" Color  :"%></strong><%= form.color_field :color %>
</div>
<div class="field" align="center">
	<%= form.submit %>
</div>

<%end%>

scaf1/app/views/cars/create.js.erb
$("#cars").html("<%= j render partial: 'car', cars: @cars %>");
$("#new_car")[0].reset();

scaf1/app/views/cars/destroy.js.erb
$("td#<%= car.m_name %>").remove();

scaf1/app/views/cars/edit.html.erb
<h1>Cars#edit</h1>
<p>Find me in app/views/cars/edit.html.erb</p>

scaf1/app/views/cars/index.html.erb
<p id="notice"><%= notice%></p>
<fieldset>
	<fieldset class="container">
		<legend align = "center"><h2>New car</h2></legend>
		<%=render 'form', car: @car%>
	</fieldset>


	<div class="container p-5 my-5 bg-warning text-white">
		<h1 align="center"> Cars List  </h1>
	</div>

	<table  class="table">
		<thead>
			<tr  align="center">
				<th scope="col"> Name </th>
				<th scope="col" align="center"> Option1 </th>
				<th scope="col" align="center"> Option2 </th>
				<th scope="col" align="center"> Option3 </th>
			
				
			</tr>
		</thead>

		<tbody id='cars'>
			<%= render partial: 'car', cars:@cars %>
		</tbody>
	</table>
</fieldset>



 <script >
	function submitMyForm(e) {
		//debugger 
	// var car_name = 	$("#car_name").val();
	// var car_quantity = $("#car_quantity").val();
	var car = $("#new_car").serialize();
	$.ajax({
		method: "post",
		url: "<%= cars_url %>", 
		data: car
	});

	}
</script>

scaf1/app/views/cars/show.html.erb
<h1>Cars#show</h1>
<p>Find me in app/views/cars/show.html.erb</p>