task2/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    resources :comments
    resources :likes
  end

  root 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

task2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

task2/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

task2/app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

task2/app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

end

task2/app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, through: :posts
 # has_many :likes, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

task2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!, except: [:index,:show]
	protect_from_forgery with: :exception
end

task2/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 def create
  #debugger
  @post = Post.find(params[:post_id])
  @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

def show
 @post = Post.find(params[:post_id])
 @comments = @post.comments.all
end 

def destroy
  @comment= Comment.find(params[:id])
  @comment.destroy

  redirect_to root_path, status: :see_other

end

private
def comment_params
  params.require(:comment).permit(:id,:post_id,:user,:comment)
end

end

task2/app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :find_post
	before_action :find_like, only: [:destroy]

	def create
		if already_liked?
			flash[:notice] = "You can't like more than once"
		else
			@post.likes.create(user_id: current_user.id)
		end
		redirect_to post_path(@post)
	end	

	def destroy
		if !(already_liked?)
			flash[:notice] = "Cannot unlike"
		else
			@like.destroy
		end
		redirect_to post_path(@post)
	end


	private
	def find_post
		@post = Post.find(params[:post_id])
	end

	def already_liked?
		Like.where(user_id: current_user.id, post_id:
			params[:post_id]).exists?
	end


	def find_like
		@like = @post.likes.find(params[:id])
	end
end

task2/app/controllers/posts_controller.rb
class PostsController < ApplicationController
	 def index
    @posts = Post.all
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.save
    @posts = Post.all
  end

  def show
    @post =Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end
  def update
    @post=Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post      
    else
      render :edit ,status: :unprocessable_entity
    end
  end

  def destroy
    @post= Post.find(params[:id])
    @post.destroy

    redirect_to root_path, status: :see_other

  end
  def like
    @post = Post.find(params[:id])
    Like.create(user_id:current_user.id, post_id:@post.id)

  end


  private
  def post_params
    params.require(:post).permit(:id,:user_id,:title,:detail)
  end
end

task2/app/helpers/application_helper.rb
module ApplicationHelper
end

task2/app/helpers/comments_helper.rb
module CommentsHelper
end

task2/app/helpers/likes_helper.rb
module LikesHelper
end

task2/app/helpers/posts_helper.rb
module PostsHelper
end

task2/app/views/posts/_form.html.erb
<%= form_with(model: @post,id:"new_post",local: false) do |form|%>
<!-- Errors code -->
<% if post.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

	<ul>
		<% post.errors.each do |error| %>
		<li><%= error.full_message %></li>
		<% end %>
	</ul>
	<%end%>
</div>
<!-- Form code start here -->

<fieldset>
	<legend><strong> Post Title</strong></legend>
	<%= form.text_field :title%>
</fieldset>
<fieldset>
	<legend><strong> Post Details </strong></legend>
	<%= form.text_area :detail%>
</fieldset>
<div class="field">
	<%= form.hidden_field :user_id, value: current_user.id %>
</div>

<div class="field" align="center">
	<%= form.submit %>
</div>

<%end%>

task2/app/views/posts/_post.html.erb
<% @posts.each do |post|%>

<tr>
	<td></td>
<td align="center"><%= post.title%></td>
<td align="center"><%= User.find(post.user_id).email %></td>

<td align="center"><%= link_to "Show", post %></td>
<% if user_signed_in? %>
<% if current_user.id == post.user_id%>
<td align="center"><%= link_to "Edit", edit_post_path(post) %></td>
<td align="center"><%= link_to "delete", post, method: :delete,remote:true,data: { confirm: 'Are you sure?' }%></td>
<%end%>
<%end%>
</tr>

<%end%>

task2/app/views/posts/create.js.erb
//debugger
$("#posts").html("<%= j render partial: 'post', posts: @posts %>");
$("#new_post")[0].reset();

task2/app/views/posts/destroy.js.erb
$("td#<%= post.title %>").remove();

task2/app/views/posts/edit.html.erb
<fieldset>
	<legend align = "center"><h2>Edit Department</h2></legend>
	<%=render 'form', department: @department%>
	<p align="center"><%= link_to "Back", :back %></p>
	<p align="center"><%= link_to "Home", root_path %></p>
</fieldset>

task2/app/views/posts/index.html.erb
<p id="notice"><%= notice%></p>

<% if user_signed_in? %>
<!--  -->
<fieldset>
	<fieldset>
		<legend align = "center"><h2>New post</h2></legend>
		<%=render 'form', post: @post%>
	</fieldset>
	<%end%>

	<table align="center">
		<thead>
			<tr>
				<th></th>
				<th >Title</th>
				<th > User Email </th>
				
			</tr>
		</thead>

		<tbody id='posts'>
			<%= render partial: 'post', posts:@posts %>
		</tbody>
	</table>
</fieldset>

task2/app/views/posts/show.html.erb
<p id="notice"><%= notice%></p>

<fieldset align = "center">
	<div class="container" align ="center"><strong> Title :</strong> <%= @post.title %></div>
	<div class="container" align ="center"><strong> Details :</strong> <%= @post.detail %></div>
	<div class="container" align ="center"><strong> User :</strong> <%= User.find(@post.user_id).email %></div>
	<% if user_signed_in? %>
	<p><%= @post.likes.count %> <%= (@post.likes.count) == 1 ? 'Like' : 'Likes'%></p>
	<% pre_like = @post.likes.find { |like| like.user_id == current_user.id} %>
<% if pre_like %>
  <%= button_to 'Unlike', post_like_path(@post, pre_like), method: :delete %>
<% else %>
  <%= button_to 'Like', post_likes_path(@post), method: :post %>
<% end %>
	<% if current_user.id == @post.user_id %>
	<p align="center"><%= link_to "Edit", edit_post_path(@post) %></p>
	<p align="center"><%= link_to "delete", @post, method: :delete,data: { confirm: 'Are you sure?' }%></p>
	<%end%>

	<%end%>
	<p align="center"><%= link_to "back", root_path %></p>
	
	<fieldset>
		<legend align= "center"> Comments</legend>
		<table>
			<thead>
				<th> Username</th>
				<th> Comment </th>
			</thead>
			<tbody id="comments">
				<%#= render @post.comments %>
				<%= render partial: 'comments/comment', comments:@comments %>
			</tbody>
		</table>
		<% if user_signed_in? %>

		<h3> Add Comment</h3>
		<%= render 'comments/form'  %>
	</fieldset>
	<%end%>
	

</fieldset>